<?php
/**
 * Local filesystem storage handler.
 *
 * Stores uploaded media in wp-content/uploads/starter-manga/ with organised
 * sub-directories per manga slug and chapter number.
 *
 * @package starter-theme
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Starter_Storage_Local
 *
 * Implements Starter_Storage_Interface for the local WordPress filesystem.
 */
class Starter_Storage_Local implements Starter_Storage_Interface {

	/**
	 * Base directory inside the uploads folder.
	 *
	 * @var string
	 */
	const UPLOAD_DIR = 'starter-manga';

	/**
	 * Resolved base path (absolute).
	 *
	 * @var string
	 */
	private $base_path = '';

	/**
	 * Resolved base URL.
	 *
	 * @var string
	 */
	private $base_url = '';

	/**
	 * Constructor.
	 */
	public function __construct() {
		$upload_dir     = wp_upload_dir();
		$this->base_path = trailingslashit( $upload_dir['basedir'] ) . self::UPLOAD_DIR;
		$this->base_url  = trailingslashit( $upload_dir['baseurl'] ) . self::UPLOAD_DIR;

		$this->maybe_create_base_directory();
	}

	/*--------------------------------------------------------------------------
	 * Starter_Storage_Interface methods.
	 *------------------------------------------------------------------------*/

	/**
	 * Upload a file to the local filesystem.
	 *
	 * @param string $file_path   Absolute local path to the source file.
	 * @param string $destination Relative destination path.
	 * @return string|WP_Error    Public URL on success, WP_Error on failure.
	 */
	public function upload( $file_path, $destination ) {
		if ( ! file_exists( $file_path ) || ! is_readable( $file_path ) ) {
			return new WP_Error(
				'starter_local_file_missing',
				__( 'Source file does not exist or is not readable.', 'starter-theme' )
			);
		}

		$destination = $this->sanitize_path( $destination );
		$target_path = trailingslashit( $this->base_path ) . $destination;
		$target_dir  = dirname( $target_path );

		// Create the directory tree.
		if ( ! wp_mkdir_p( $target_dir ) ) {
			return new WP_Error(
				'starter_local_mkdir_fail',
				__( 'Could not create destination directory.', 'starter-theme' )
			);
		}

		// Protect the directory with .htaccess (directory listing off).
		$this->protect_directory( $target_dir );

		// Attempt image optimisation before writing.
		$optimised = $this->maybe_optimise_image( $file_path );
		$source    = $optimised ? $optimised : $file_path;

		// Copy (do not move) so the temp file is still available for fallback.
		if ( ! copy( $source, $target_path ) ) {
			return new WP_Error(
				'starter_local_copy_fail',
				__( 'Could not copy the file to the destination.', 'starter-theme' )
			);
		}

		// Set safe permissions.
		chmod( $target_path, 0644 );

		// Clean up temp optimised file if created.
		if ( $optimised && $optimised !== $file_path ) {
			@unlink( $optimised );
		}

		return $this->get_url( $destination );
	}

	/**
	 * Delete a file from local storage.
	 *
	 * @param string $path Relative path.
	 * @return bool
	 */
	public function delete( $path ) {
		$path      = $this->sanitize_path( $path );
		$full_path = trailingslashit( $this->base_path ) . $path;

		if ( ! file_exists( $full_path ) ) {
			return false;
		}

		return wp_delete_file_from_directory( $full_path, $this->base_path );
	}

	/**
	 * Get the public URL.
	 *
	 * @param string $path Relative path.
	 * @return string
	 */
	public function get_url( $path ) {
		$path = $this->sanitize_path( $path );
		return trailingslashit( $this->base_url ) . $path;
	}

	/**
	 * Check if a file exists locally.
	 *
	 * @param string $path Relative path.
	 * @return bool
	 */
	public function exists( $path ) {
		$path      = $this->sanitize_path( $path );
		$full_path = trailingslashit( $this->base_path ) . $path;
		return file_exists( $full_path );
	}

	/*--------------------------------------------------------------------------
	 * Internal helpers.
	 *------------------------------------------------------------------------*/

	/**
	 * Ensure the base upload directory exists and is protected.
	 *
	 * @return void
	 */
	private function maybe_create_base_directory() {
		if ( ! is_dir( $this->base_path ) ) {
			wp_mkdir_p( $this->base_path );
		}
		$this->protect_directory( $this->base_path );
	}

	/**
	 * Drop an .htaccess in the given directory to disable directory listing
	 * and optionally restrict access.
	 *
	 * @param string $dir Absolute directory path.
	 * @return void
	 */
	private function protect_directory( $dir ) {
		$htaccess = trailingslashit( $dir ) . '.htaccess';

		if ( file_exists( $htaccess ) ) {
			return;
		}

		$rules = <<<'HTACCESS'
# Generated by starter-theme — do not edit.
Options -Indexes

# Only allow image and video MIME types to be served.
<FilesMatch "\.(jpe?g|png|gif|webp|avif|bmp|svg|mp4|webm|mkv)$">
    <IfModule mod_authz_core.c>
        Require all granted
    </IfModule>
</FilesMatch>

# Block everything else.
<FilesMatch "\.php$">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order deny,allow
        Deny from all
    </IfModule>
</FilesMatch>
HTACCESS;

		@file_put_contents( $htaccess, $rules );
	}

	/**
	 * Sanitize a relative storage path.
	 *
	 * Prevents directory traversal and normalises slashes.
	 *
	 * @param string $path Raw path.
	 * @return string Clean path.
	 */
	private function sanitize_path( $path ) {
		// Remove null bytes.
		$path = str_replace( "\0", '', $path );

		// Normalise directory separators.
		$path = str_replace( '\\', '/', $path );

		// Remove any traversal attempts.
		$path = str_replace( '../', '', $path );
		$path = str_replace( '..\\', '', $path );

		// Remove leading slashes.
		$path = ltrim( $path, '/' );

		// Sanitise each segment.
		$parts     = explode( '/', $path );
		$sanitised = array();

		foreach ( $parts as $part ) {
			$part = sanitize_file_name( $part );
			if ( '' !== $part && '.' !== $part && '..' !== $part ) {
				$sanitised[] = $part;
			}
		}

		return implode( '/', $sanitised );
	}

	/**
	 * Attempt to optimise an image file using GD or Imagick.
	 *
	 * Returns the path to an optimised temp copy, or false if optimisation
	 * is unavailable or the file is not an image.
	 *
	 * @param string $file_path Absolute path to the source file.
	 * @return string|false     Path to optimised temp file, or false.
	 */
	private function maybe_optimise_image( $file_path ) {
		$mime = wp_check_filetype( $file_path );

		if ( empty( $mime['type'] ) || 0 !== strpos( $mime['type'], 'image/' ) ) {
			return false;
		}

		// Skip SVG — nothing to rasterise.
		if ( 'image/svg+xml' === $mime['type'] ) {
			return false;
		}

		// Try WordPress built-in editor (which delegates to Imagick or GD).
		$editor = wp_get_image_editor( $file_path );

		if ( is_wp_error( $editor ) ) {
			return false;
		}

		// Set reasonable quality.
		$editor->set_quality( apply_filters( 'starter_storage_image_quality', 82 ) );

		$tmp = wp_tempnam( $file_path );

		$saved = $editor->save( $tmp, $mime['type'] );

		if ( is_wp_error( $saved ) ) {
			@unlink( $tmp );
			return false;
		}

		// Only use the optimised version if it is actually smaller.
		if ( filesize( $saved['path'] ) < filesize( $file_path ) ) {
			return $saved['path'];
		}

		@unlink( $saved['path'] );
		return false;
	}

	/*--------------------------------------------------------------------------
	 * Public utilities.
	 *------------------------------------------------------------------------*/

	/**
	 * Get the absolute base path for local storage.
	 *
	 * @return string
	 */
	public function get_base_path() {
		return $this->base_path;
	}

	/**
	 * Get the full absolute path for a relative storage path.
	 *
	 * @param string $path Relative path.
	 * @return string Absolute path.
	 */
	public function get_absolute_path( $path ) {
		return trailingslashit( $this->base_path ) . $this->sanitize_path( $path );
	}
}
